FROM ubuntu:latest

RUN useradd -ms /bin/zsh user

RUN apt-get update -qq && \
    apt-get upgrade -qqy && \
	apt-get install -qqy \
		apt-transport-https \
		wget curl \
		git \
		vim \
		libpq-dev \
		bash zsh \
		python3 python3-dev python3-pip

COPY --chown=user:user dotfiles /home/user/dotfiles
RUN  mkdir -p /home/user/.local/share/zsh \
	&& /bin/su -s /bin/zsh -c "/home/user/dotfiles/install.sh" user

COPY --chown=user:user entrypoint.sh entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
