FROM ubuntu:latest

COPY installCommonPackages.sh ./
RUN ./installCommonPackages.sh # common packages has node...

# Python specific stuff
RUN apt install -qqy python3 python3-dev python3-pip

COPY entrypoint.sh ./
CMD [ "./entrypoint.sh" ]
