FROM ubuntu:latest

RUN useradd -ms /bin/zsh user

RUN apt-get update -qq && \
	apt-get install -qqy \
		wget curl \
		git vim bash zsh

COPY --chown=user:user dotfiles /home/user/dotfiles
RUN  mkdir -p /home/user/.local/share/zsh \
	&& /bin/su -s /bin/zsh -c "/home/user/dotfiles/install.sh" user

COPY --chown=user:user entrypoint.sh entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
