FROM ubuntu:latest

RUN apt-get update -qq && \
	apt-get install -qqy \
		wget curl \
		git vim zsh

# we should not do everything as root. Bad practice.
RUN useradd -ms /bin/zsh user
USER user
WORKDIR /home/user

COPY --chown=user:user dotfiles /home/user/dotfiles

RUN  mkdir -p /home/user/.local/share/zsh \
	&& /home/user/dotfiles/install.sh

ENTRYPOINT [ "/bin/zsh" ]
